version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  
  commands:
    - conda init bash
    - conda env create -f docs/environment.yaml
    - conda activate docs
    - candi-install
