version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  
conda:
  environment: docs/environment.yaml

build:
  steps:
  - name: Install CanDI (i.e. download required datasets)
    run: |
      candi-install