version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  
  commands:
    - conda create -f docs/environment.yaml
    - candi-install