version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/environment.yaml

  jobs:
    pre_create_environment:
      - echo "Command run at 'pre_create_environment' step"
      - candi-install
    post_build:
      - echo "Command run at 'post_build' step"
      - echo `date`