name: docs
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>=3.11,<4.0
  - myst-parser
  - sphinx>=7.0.0
  - jinja2<=3.1
  - pandas
  - numpy
  - polars
  - configparser
  - requests
  - tqdm
  - pip
  - pip:
    - myst-nb
    - sphinx_rtd_theme
    - pydeseq2
    - adpbulk
    - pycandi
