name: docs
channels:
  - anaconda
  - conda-forge
dependencies:
  - myst-parser=0.18.1
  - sphinx=5.3.0
  - sphinx_rtd_theme=1.1.1
  - jinja2<=3.1
  - pandas
  - polars
  - pip
  - pip:
    - nbsphinx
    - pycandi
