name: docs
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - sphinx==3.2.1
  - jinja2<=3.1
  - pandas
  - pip
  - pip:
    - nbsphinx
    - sphinx_rtd_theme==0.4.3
